# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-CDBaby
version:      0.04
version_from: lib/WWW/CDBaby.pm
installdirs:  site
requires:
    Test::More:                    0
    WWW::Sitebase::Navigator:      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
